services:
  # Backend service
  - type: web
    name: cyber-chatbot-backend
    env: python
    plan: starter  # Free tier
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: JWT_SECRET_KEY
        generateValue: true  # Render will auto-generate a secure key
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
      - key: MAX_CONCURRENT_CALLS
        value: "1"
      - key: MIN_CALL_INTERVAL_SECONDS
        value: "1.5"
    
  # Frontend service (static site)
  - type: static
    name: cyber-chatbot-frontend
    plan: starter  # Free tier
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: cyber-chatbot-backend
          property: url
